version: '3.8'

services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=ecommerce
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
    working_dir: /app
    command: "./start.sh"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./server/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  app_network:

volumes:
  db_data:
