version: '3.8'

services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
    working_dir: /app
    command: "./start.sh"
    networks:
      - app_network

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

networks:
  app_network:

volumes:
  db_data:
